language: go

os:
  - windows
  - linux
  - osx

go:
  - "1.12.x"

before_script:
- go get github.com/c-bata/go-prompt
- go get -v github.com/mattn/go-colorable
- go get -v github.com/mattn/go-tty
- go get github.com/mattn/goveralls
- go get -d -v ./...

env:
  - CONTEXT=abs

script: 
 - go test ./... -vet=off -v -covermode=count -coverprofile=coverage.out
 - $GOPATH/bin/goveralls -service=travis-ci -coverprofile=coverage.out